server:
  host: "0.0.0.0"
  port: 5432
  mode: "rw"
  min_timeout_ms: 100
  max_timeout_ms: 2000
replicas: []
logs:
  con: True
  file: "./database.log"
  server:
    host: "0.0.0.0"
    port: 20000

